version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: nest-api
    # environment:
        # essa variável de ambiente vai interferir no node, significa que eu
        # trabalhando nesse projeto va rede porque eu estou dentro do container
        # mas estou editando os arquivos na minha máquina e tem o volume
        # compartilhado
    #   - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_api

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9001:80"
    depends_on:
      - db
